name: bump version on tag

on:
    create:
        tags:
            - 'v*.*.*'

jobs:
    bump-version:
        runs-on: ubuntu-latest

        steps:
        - name: testing
          run: echo $REF
          env:
              REF: ${{ github.ref }}
