name: PR Labels

on:
    pull_request:

jobs:
    enforce-label:
        runs-on: ubuntu-latest
        steps:
            - name: check for major
              id: major
              if: ${{ contains(github.event.pull_request.labels.*.name, 'major') }}
              run: |
                  echo "::set-output name=exists::1"

            - name: check for minor
              id: minor
              if: ${{ contains(github.event.pull_request.labels.*.name, 'minor') }}
              run: |
                  echo "::set-output name=exists::1"

            - name: check for patch
              id: patch
              if: ${{ contains(github.event.pull_request.labels.*.name, 'patch') }}
              run: |
                  echo "::set-output name=exists::1"

            - name: check for other
              id: other
              if: ${{ contains(github.event.pull_request.labels.*.name, 'other') }}
              run: |
                  echo "::set-output name=exists::1"

            - name: ensure exclusivity
              run: |
                  if [ -z "$IS_MAJOR" ] && [ -z "$IS_MINOR" ] && [ -z "$IS_PATCH" ] && [ -z "$IS_OTHER" ];
                  then
                    echo There are no labels; need one from the following: ['major', 'minor', 'patch', 'other']
                    exit 1
                  fi

                  SUM=$(($IS_MAJOR + $IS_MINOR + $IS_PATCH + $IS_OTHER))

                  HAS_ONLY_ONE_LABEL=$(($SUM == 1))

                  if [ $HAS_ONLY_ONE_LABEL = 0 ]; then
                    echo Has multiple labels
                    exit 1
                  fi
              env:
                  IS_MAJOR: ${{ steps.major.outputs.exists }}
                  IS_MINOR: ${{ steps.minor.outputs.exists }}
                  IS_PATCH: ${{ steps.patch.outputs.exists }}
                  IS_OTHER: ${{ steps.other.outputs.exists }}
