name: PR Labels

on:
    pull_request:
    label:

jobs:
    enforce-label:
        runs-on: ubuntu-latest
        steps:
            - name: require label
              if: ${{ !contains(github.event.label.name, 'major') || !contains(github.event.label.name, 'minor') || !contains(github.event.label.name, 'patch') || !contains(github.event.label.name, 'other')}}
              run: |
                  echo ${{ github.event.label.name }}
                  echo Need a label ['major', 'minor', 'patch', 'other']
                  exit 1
