name: PR Labels

on:
    pull_request:
    label:

jobs:
    enforce-label:
        runs-on: ubuntu-latest
        steps:
            - name: get labels
              id: get_labels
              run: |
                  echo "::set-output name=labels::$LABELS"
              env:
                  LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}

            - name: check for major
              if: ${{ contains(steps.get_labels.outputs.labels, 'major') }}
              run: |
                  echo "isMajor=1" >> $GITHUB_ENV

            - name: check for minor
              if: ${{ contains(steps.get_labels.outputs.labels, 'minor') }}
              run: |
                  echo "isMinor=1" >> $GITHUB_ENV

            - name: check for patch
              if: ${{ contains(steps.get_labels.outputs.labels, 'patch') }}
              run: |
                  echo "isPatch=1" >> $GITHUB_ENV

            - name: check for other
              if: ${{ contains(steps.get_labels.outputs.labels, 'other') }}
              run: |
                  echo "isOther=1" >> $GITHUB_ENV

            - name: ensure exclusivity
              run: |
                  DOES_NOT_HAVE_ONE_LABEL = $((($isMajor + $isMinor + $isPatch + $isOther) != 1))

                  if $DOES_NOT_HAVE_ONE_LABEL; then
                    echo "Need one label from the following: ['major', 'minor', 'patch', 'other']"
                    exit 1
                  fi
