name: PR Labels

on:
    pull_request:
    label:

jobs:
    enforce-label:
        runs-on: ubuntu-latest
        steps:
            - name: check for major
              if: ${{ contains(toJson(github.event.pull_request.labels.*.name), 'major') }}
              run: |
                  echo "isMajor=1" >> $GITHUB_ENV

            - name: check for minor
              if: ${{ contains(toJson(github.event.pull_request.labels.*.name), 'minor') }}
              run: |
                  echo "isMinor=1" >> $GITHUB_ENV

            - name: check for patch
              if: ${{ contains(toJson(github.event.pull_request.labels.*.name), 'patch') }}
              run: |
                  echo "isPatch=1" >> $GITHUB_ENV

            - name: check for other
              if: ${{ contains(toJson(github.event.pull_request.labels.*.name), 'other') }}
              run: |
                  echo "isOther=1" >> $GITHUB_ENV

            - name: ensure exclusivity
              run: |
                  echo $(($isMajor + $isMinor + $isPatch + $isOther))
                  DOES_NOT_HAVE_ONE_LABEL = $((($isMajor + $isMinor + $isPatch + $isOther) != 1))

                  if [ $DOES_NOT_HAVE_ONE_LABEL ] then
                    echo "Need one label from the following: ['major', 'minor', 'patch', 'other']"
                    exit 1
                  fi
