name: lint
on:
    push:
    pull_request:
        branches:
            - '**'

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8, 3.9]
            fail-fast: false

        steps:
            - name: check out repo
              uses: actions/checkout@v2

            - name: set up python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: set up node
              uses: actions/setup-node@v2
              with:
                  node-version: '12'

            - name: Install Poetry Action
              uses: snok/install-poetry@v1.1.1
              with:
                  version: 1.1.4
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v2
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

            - name: install poetry dependencies
              run: poetry install
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

            - name: load cached npm
              id: cached-npm-dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

            - name: install pyright dependencies
              run: sudo npm install -g pyright
              if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'

            - name: lint
              run: |
                  poetry run poe typing
                  poetry run poe lint
                  poetry run poe sort-imports
