name: unit-test
on:
    push:
    pull_request:
        branches:
            - '**'

jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.8, 3.9]
            fail-fast: false

        steps:
            - name: check out repo
              uses: actions/checkout@v2

            - name: set up python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install Poetry Action
              uses: snok/install-poetry@v1.1.1
              with:
                  version: 1.1.4
                  virtualenvs-create: true
                  virtualenvs-in-project: true

            - name: load cached venv
              id: cached-poetry-dependencies
              uses: actions/cache@v2
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

            - name: install poetry dependencies
              run: poetry install
              if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

            - name: test
              run: |
                  poetry shell
                  poe test-coverage
                  coverage report

            - name: upload coverage
              uses: codecov/codecov-action@v1
              fail_ci_if_error: true
              verbose: true
